package communication;

public interface RequestAction {
    String LOGIN_FARMER = "LOGIN FARMER";
    String CHECK_IF_FARMER_EMAIL_ALREADY_EXISTS = "CHECK IF FARMER EMAIL ALREADY EXISTS";
    String CREATE_FARMER = "CREATE FARMER";
    String UPDATE_FARMER_EARNINGS = "UPDATE FARMER EARNINGS";
    String GET_FARMER_CUSTOMERS = "GET FARMER CUSTOMERS";

    String LOGIN_CUSTOMER = "LOGIN_CUSTOMER";
    String CHECK_IF_CUSTOMER_EMAIL_ALREADY_EXISTS = "CHECK IF CUSTOMER EMAIL ALREADY EXISTS";
    String CREATE_CUSTOMER = "CREATE CUSTOMER";
    String GET_CUSTOMER_TOTAL_BASKET = "GET CUSTOMER TOTAL BASKET";
    String GET_CUSTOMER_FUNDS = "GET CUSTOMER FUNDS";
    String UPDATE_CUSTOMER_FUNDS = "UPDATE CUSTOMER FUNDS";
    String CHECK_IF_CUSTOMER_BASKET_EMPTY = "CHECK IF CUSTOMER BASKET EMPTY";
    String UPDATE_FOR_CHECKOUT = "UPDATE FOR CHECKOUT";
    String REMOVE_ITEM_FROM_CUSTOMER_BASKET = "REMOVE ITEM FROM CUSTOMER BASKET";
    String UPDATE_CUSTOMER_BASKET_CROP_QUANTITY = "UPDATE CUSTOMER BASKET CROP QUANTITY";
    String GET_CROP_UNIT_COST_FROM_CUSTOMER_BASKET = "GET CROP UNIT COST FROM CUSTOMER BASKET";
    String UPDATE_CUSTOMER_BASKET_CROP_TOTAL = "UPDATE CUSTOMER BASKET CROP TOTAL";
    String ADD_CROP_TO_CUSTOMER_BASKET = "ADD CROP TO CUSTOMER BASKET";
    String CUSTOMER_VIEW_BASKET = "CUSTOMER VIEW BASKET";

    String ADD_CROP = "ADD CROP";
    String UPDATE_CROP = "UPDATE CROP";
    String UPDATE_CROP_WITH_IMAGE = "UPDATE CROP WITH IMAGE";
    String GET_FARMER_CROPS_UPDATE_CROPS = "GET FARMER CROPS UPDATE CROPS";
    String GET_FARMER_CROPS_VIEW_CROPS = "GET FARMER CROPS VIEW CROPS";
    String GET_CUSTOMER_VIEW_CROPS = "GET CUSTOMER VIEW CROPS";
    String GET_CUSTOMER_VIEW_CROPS_FARMER_SEARCH = "GET CUSTOMER VIEW CROPS FARMER SEARCH";
    String CHECK_IF_CROP_ALREADY_EXISTS_FOR_FARMER = "CHECK IF CROP ALREADY EXISTS FOR FARMER";
    String UPDATE_CROP_QUANTITY_USING_ID = "UPDATE CROP QUANTITY USING ID";


    String LOGOUT = "LOGOUT";
    String DISCONNECT = "DISCONNECT";

    String ADD_TO_ONLINE_LIST = "ADD TO ONLINE LIST";
    String REMOVE_FROM_ONLINE_LIST = "REMOVE FROM ONLINE LIST";
    String GET_FARMERS_AVAILABLE_FOR_CHAT = "GET FARMERS AVAILABLE FOR CHAT";
    String END_LIVE_CHAT = "END LIVE CHAT";
    String FORWARD_MESSAGE = "FORWARD MESSAGE";
    String RECEIVE_MESSAGE = "RECEIVE MESSAGE";
    String HANDLE_SEND_MESSAGE_RESPONSE = "HANDLE SEND MESSAGE RESPONSE";
    String START_FARMER_LIVE_CHAT = "START FARMER LIVE CHAT";

}
